spring:
  application:
    name: SimpleSecureCipher
  datasource:
    url: jdbc:mysql://mysql:3306/your-db
    username: your-username
    password: your-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
jwt:
  secret: your-secret-key
  expiration: 3600000 # 1 hour

